global:
  scrape_interval: 2s

scrape_configs:
  # Arma Metrics
  - job_name: 'arma-metrics-py'
    static_configs:
      - targets: ['arma-metrics-py:8880']
  # Node Exporter 
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
