{
 "title": "Arma Reforger Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Players",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_players", "legendFormat": "__auto" },
    { "expr": "server_ai", "legendFormat": "__auto" },
    { "expr": "server_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FPS // KI Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "server_fps", "legendFormat": "__auto" },
    { "expr": "server_ai", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vehicle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "server_veh_count", "legendFormat": "__auto" },
    { "expr": "server_veh_extra_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 7 },
   "targets": [
    { "expr": "server_players", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Projectiles TOTAL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_proj_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Packet Loss %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_avg_pktloss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RoundTripTime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_avg_rtt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Projectiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "targets": [
    { "expr": "server_proj_shells", "legendFormat": "__auto" },
    { "expr": "server_proj_missiles", "legendFormat": "__auto" },
    { "expr": "server_proj_grenades", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RTT and Packet Loss Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    { "expr": "server_avg_rtt", "legendFormat": "__auto" },
    { "expr": "server_avg_pktloss", "legendFormat": "__auto" }
   ]
  }
 ]
}